### ISSUE TITLE
Hello,why this happens when I use IE8 or 360 Explorer?

### ISSUE THREAD

**Issue by zeryo** [lloyd/myfavoritebeer.org#17]
When  I click login , it can't display properly, and I can't login. But when I use Google Chrome, it's well.Thank you.

**Comment by lloyd** [comment]
should be fixed!  Try http://dev.myfavoritebeer.org - the production site (http://myfavoritebeer.org) will be updated shortly with IE support.

**Comment by zeryo** [comment]
I will try. Thank you very much!
