### ISSUE TITLE
Why not use OpenID?

### ISSUE THREAD

**Issue by Realcool** [lloyd/myfavoritebeer.org#2]
I'm not sure where to ask this, but   Why not use OpenID instead? Is not it better to ask to webmasters give support for OpenID, which already exists? What is the difference?

If there exists a difference, perhaps you should allow associate an OpenID as an alternative to e-mail.

**Comment by polymorphm** [comment]
if we say "OpenID"  -- we think "OpenID+WebFinger"

**Comment by lloyd** [comment]
@Realcool -- @benadida spent some time trying to outline the differences between browserid and openid, and in turn lays bare mozilla's motivation for building browserid.  Give it a read: http://identity.mozilla.com/post/7669886219/how-browserid-differs-from-openid
