### ISSUE TITLE
Won't show my fav beer in private modes.

### ISSUE THREAD

**Issue by ifmusic** [lloyd/myfavoritebeer.org#4]
The sample works perfect in "normal" mode. If I switch to Private (ffox) or Incognito (chorme), after getting authenticated the site doesn't show any beer preference!

**Comment by lloyd** [comment]
This is because right now the demo is just a hacked up demonstration of login flow.  Once we build a little tiny server component to demonstrate more of the mechanics of integration, this issue should be addressed as well.  leaving open!

**Comment by ifmusic** [comment]
Great! I thought It was worth mentioning. Nice work!

**Comment by lloyd** [comment]
should be fixed now on http://dev.myfavoritebeer.org.  Give it a whirl.
