### ISSUE TITLE
The header and the footer of https://beta.myfavoritebeer.org are not displayed in IE8

### ISSUE THREAD

**Issue by ghost** [lloyd/myfavoritebeer.org#42]
OS: Windows XP
Browser: IE8

STR:
1. Launch https://beta.myfavoritebeer.org in the browser.
2. Click on the "Continue to this website" link.

The website content is displayed, except for the header and the footer. Since the Sign In button is on the header, the button is missing from the page and the user cannot log in.

Note:
This issue doesn't reproduce on the latest Firefox and Chrome versions.

**Comment by shane-tomlinson** [comment]
Clsoing as fixed.
