### ISSUE TITLE
Question: Have you approached GitHub to adopt this?

### ISSUE THREAD

**Issue by chrisjacob** [lloyd/myfavoritebeer.org#6]
Hi there,

I notice GitHub is mentioned on https://browserid.org/primaries (p.s. perhaps consider Capitalising their business name)... have they made any indication of interest in this yet?

Looks like an interesting project.

Best of luck ^_^
- Chris

**Comment by lloyd** [comment]
Hey Chris,

No, we haven't talked to GitHub about BrowserID.  Might be useful to do so at some point.

Thanks for writing!
lloyd
