### ISSUE TITLE
Purely Client Side?... or do implementers still need a server?

### ISSUE THREAD

**Issue by chrisjacob** [lloyd/myfavoritebeer.org#7]
I noticed the following comment in:

https://github.com/lloyd/myfavoritebeer.org/blob/master/static/js/main.js

"WARNING: This is only an example. In real apps, this verification step must be done from server-side code. "

Can BrowserID securely support a purely client side login system?... i.e. no server at all for developers implementing it. This is what I was hoping for ^_^

If I recall correctly, Twitter @Anywhere seems to have a system that is just clientside javascript. https://dev.twitter.com/docs/anywhere/welcome ... not sure if that's relevant :-P

Cheers,
Chris

**Comment by lloyd** [comment]
this is fixed.  the app is now a real client-server application.  I'll host it and write some better documentation, as well as annotating and describing the code.
